#import = ["~/.config/alacritty/colorschemes/catppuccin-macchiato.toml"]
#import = ["~/.config/alacritty/colorschemes/catppuccin-mocha.toml"]
#import = ["~/.config/alacritty/colorschemes/rose-pine.toml"]
import = ["~/.config/alacritty/colorschemes/gruvbox_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
# for mac
option_as_alt = "Both"

[window.padding]
x = 5
y = 5

[font]
size = 18
 [font.normal]
 family = "MesloLGM Nerd Font"
 style = "Regular" 
 [font.bold]       
 family = "MesloLGM Nerd Font"
 style = "Bold"    
 [font.italic]     
 family = "MesloLGM Nerd Font"
 style = "Italic"
#[font.normal]
#family = "RobotoMono Nerd Font" 
#style = "Regular"
#[font.bold]
#family = "RobotoMono Nerd Font"
#style = "Bold"
#[font.italic]
#family = "RobotoMono Nerd Font"
#style = "Italic"
